### ISSUE TITLE
error from install_github("wkopp/motifcounter")

### ISSUE THREAD

**Issue by shouyongpeng** [wkopp/motifcounter#2]
Downloading GitHub repo wkopp/motifcounter@master
from URL https://api.github.com/repos/wkopp/motifcounter/zipball/master
Installing motifcounter
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/01/1xnkk3m530788bczxnbznbtr0000gp/T/RtmpR2z5H8/devtools14fe9237cab68/wkopp-motifcounter-87cfd05'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘motifcounter’ ...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include  -fopenmp -DIN_R -fPIC  -Wall -g -O2  -c Rbackground.c -o Rbackground.o
**clang: error: unsupported option '-fopenmp'**
make: *** [Rbackground.o] Error 1
ERROR: compilation failed for package ‘motifcounter’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/motifcounter’
Installation failed: Command failed (1)

**Comment by wkopp** [comment]
Apparently, clang does support openMP (https://clang.llvm.org/docs/UsersManual.html#openmp-features). Did you install a clang version with openMP support?

Also, could you try to install motifcounter from bioconductor directly using
```
source("https://bioconductor.org/biocLite.R")
biocLite("motifcounter")
```
